// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for windows - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return null;
      case TargetPlatform.linux:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for linux - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return null;
      default:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions are not supported for this platform.',
        // );
        return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3Hexe5W0NvVWTng6T0cS7IVb0yL8hW0',
    appId: '1:555411122478:web:993bcc8a918cbf7e43b2bf',
    messagingSenderId: '555411122478',
    projectId: 'shali-7e651',
    authDomain: 'shali-7e651.firebaseapp.com',
    storageBucket: 'shali-7e651.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMfbZWVB-sEZIFd3H1mT6YSEXHBYMUX4Y',
    appId: '1:555411122478:android:406f7607d15b867b43b2bf',
    messagingSenderId: '555411122478',
    projectId: 'shali-7e651',
    storageBucket: 'shali-7e651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-zhgNFDpoysSQ0q0pP_8wZ5XFXzc4N8',
    appId: '1:555411122478:ios:ec5877eb1f69541043b2bf',
    messagingSenderId: '555411122478',
    projectId: 'shali-7e651',
    storageBucket: 'shali-7e651.appspot.com',
    iosClientId:
        '555411122478-o02u742vognkpmp404m63hqlpq3eh0ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaliFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-zhgNFDpoysSQ0q0pP_8wZ5XFXzc4N8',
    appId: '1:555411122478:ios:b63aa415703cb97443b2bf',
    messagingSenderId: '555411122478',
    projectId: 'shali-7e651',
    storageBucket: 'shali-7e651.appspot.com',
    iosClientId:
        '555411122478-b11ht2877lcs3l07f06htjv2i9bj44bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaliFe.RunnerTests',
  );
}
